version: '3.9'

networks:
  monitoring:
    driver: bridge


services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    networks:
      - monitoring
    volumes:
     # - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    container_name: timescaledb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data
    networks:
      - monitoring

  pythonworker:
    build: /pythonworker/
    restart: unless-stopped
    container_name: pythonworker
    volumes:
      - type: bind 
        source: /pythonworker/
        target: /scripts/
    networks:
      - monitoring



volumes:
  prom_data:
